client_config_backend: settings
client_config:
  client_id: 86584411651-339klhd4djg2m7nebhp3spggh4l9dagm.apps.googleusercontent.com
  client_secret: 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
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file